defaults:
  - scope:
      path: ""
      type: dnd
    values:
      layout: page
  - scope:
      path: ""
      type: informatica
    values:
      layout: page

title: WikiCueva
lang: es
description: El centro de información de La Cueva. Información variada sobre temas variados.
baseurl: "" # subpath, e.g. /blog
url: "" # without trailing /
github_url:  PabloClon/wikicueva
github_title: wikicueva
google_analytics: UA-55358979-9

collections:
  dnd:
    title: D&D
    output: true
    permalink: /dnd/:path/

  informatica:
    title: Ingeniería Informática
    output: true
    permalink: /informatica/:path/

relative_links:
  enabled: true
  collections: true
gist:
  noscript: false

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-gist

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
